### PR TITLE
19 wifi support

### PR DESCRIPTION
**Pull request by zjcers**
Fixes issue #19 

## List of Changes

 - Implemented initial wifi HAL in radioapp
 - Added wifi icons to main screen
 - Enabled wpa_supplicant in buildroot configuration
 - Added automatic IP address configuration based on wifi status

### CODE REVIEW

**Review by aamirani — APPROVED** [review]

**Comment by zjcers** [comment]
Still needs to be tested on device, but the icon when running on my machine

**Review by AstralA — DISMISSED** [review]
Doesn't run on my machine.

**Comment by zjcers** [comment]
@AstralA I'm going to need more information than "doesn't work":
* What was the error message/traceback?
* What OS are you on? It **must** be Linux with DBus running.
* Did you make sure to install the newly-introduced dependency?

**Comment by AstralA** [comment]
There are syntax errors in home.py
Here is the error I'm getting once that's fixed.
self.icons = resources.Resources()
NameError: name 'resources' is not defined

**Comment by zjcers** [comment]
Hmmm... `resources` is defined by an `import` on line 3 of the `home.py` that's checked into this branch. I'm not sure how it's not defined on your machine.

**Comment by zjcers** [comment]
Note: there's still a few things I need to do before this is complete (that is, the board support portion of this is not finished and vetted)

**Comment by zjcers** [comment]
This is ready to go. I also added the ability to use DHCP to get IP addresses as needed, so wifi is more or less good enough as of this PR

**Pull request merged**
